plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

remote_theme: pmarsceill/just-the-docs
title: Electronics A-Level {: .fs-10 }

heading_anchors: true
nav_enabled: true
nav_external_links:
  -title: Testing Navigation
  url: https://mossicj.github.io/ElectronicsALevel
