plugins:
  - jekyll-remote-theme

remote-theme: benbalter/retlab
title: Cirencester College Electronics A-Level booklet organisation
description: Bookmark this to keep easy navigation of the electronics booklets!
