plugins:
  - jekyll-remote-theme

remote-theme: just-the-docs/just-the-docs
title: Cirencester College Electronics A-Level booklet organisation
description: Bookmark this to keep easy navigation of the electronics booklets!
